### PR TITLE
now set ijento script from / url

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by wheresrhys** [comment]
Don't merge before
- https://github.com/Financial-Times/next-article/pull/1201
- https://github.com/Financial-Times/next-express/pull/291
- https://github.com/Financial-Times/next-ijento/pull/17

**Comment by commuterjoy** [comment]
Forgot to say, it's important that we check with web analytical team after this change to check page view stats are _normal_.

**Comment by wheresrhys** [comment]
yep mark stephens or someone else?

**Comment by commuterjoy** [comment]
Tom woolrich

**Pull request merged**
